<a href="https://colab.research.google.com/github/ledangnam20146507/AI-Course-Homework-1/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from sklearn.linear_model import Perceptron
x=[[0,0],[0,1],[1,0],[1,1]]
t=[0,1,1,1]
model=Perceptron()
model.fit(x,t)
model.score(x,t)
x1=[[0.5,1],[0.5,0.5],[-10,1]]
y1=model.predict(x1)
print(y1)
model.score(x1,y1)

[1 1 0]


1.0

In [12]:
x=[[-0.5,-0.5],[-0.5,0.5],[0.5,0.5],[-0.5,1]]
t=[1,1,0,0]
model=Perceptron()
model.fit(x,t)
model.score(x,t)
x1=[[0,0],[0.4,0.3]]
y1=model.predict(x1)
print(y1)
model.score(x1,y1)

[0 0]


1.0

In [53]:
from numpy.core.fromnumeric import shape
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np


iris=datasets.load_iris()


shape(iris)
x=iris.data
y=iris.target
print(x[:5])
print(y[:5])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)

model=Perceptron(max_iter=10000,eta0=0.01,random_state=0)
model.fit(x_train_std,y_train)
y_pred=model.predict(x_test_std)
print(y_pred)
print(y_test)
print('độ chính xác của màn hình:',accuracy_score(y_test,y_pred))



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[1 0 1 1 2 2 1 2 0 2 0 1 2 0 1 0 1 2 0 0 1 0 0 2 0 1 1 0 0 1 2 0 0 0 0 1 1
 0 1 0 2 0 2 2 0]
[1 0 1 1 2 2 1 1 0 2 0 1 2 0 1 0 1 2 0 0 1 0 0 2 0 1 1 0 0 1 2 0 0 0 0 1 1
 0 1 0 2 0 2 2 0]
độ chính xác của màn hình: 0.9777777777777777


In [61]:
from pandas.io.formats.style_render import DataFrame
from numpy.core.fromnumeric import shape
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
url='crabs.csv'
data=pd.read_csv(url)
data.shape
data.head()
df=pd.DataFrame(data)
data.drop(data.index[100:200],axis=0, inplace=True)
data.shape

data.replace(to_replace="M",value=0, inplace=True)
data.replace(to_replace="F",value=1, inplace=True)
data.head()

data.drop(data.columns[[0,2]], axis=1, inplace=True)
data.head()

X = data[['fontallip', 'rearwidth', 'length', 'width', 'depth']].to_numpy()
y = data['sex'].to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

model = Perceptron(max_iter=1000, eta0=0.1, random_state=0) 
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print("Do chinh xac cua mo hinh: ", accuracy_score(y_test,y_pred))



[1 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0]
Do chinh xac cua mo hinh:  0.9333333333333333
